"""add phone number to users table

Revision ID: 916ff2fe0b49
Revises: 9fb77ee5cf19
Create Date: 2024-09-07 17:21:32.014157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916ff2fe0b49'
down_revision = '9fb77ee5cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
